SELECT
  "Courses".course_id,
  "Courses".all_course_codes,
  "Courses".areas,
  ("Courses".average_gut_rating) :: numeric(10, 3) AS average_gut_rating,
  ("Courses".average_professor) :: numeric(10, 3) AS average_professor,
  ("Courses".average_rating) :: numeric(10, 3) AS average_rating,
  ("Courses".average_workload) :: numeric(10, 3) AS average_workload,
  ("Courses".average_rating_same_professors) :: numeric(10, 3) AS average_rating_same_professors,
  ("Courses".average_workload_same_professors) :: numeric(10, 3) AS average_workload_same_professors,
  "Courses".classnotes,
  "Courses".course_code,
  ("Courses".credits) :: numeric(10, 3) AS credits,
  "Courses".crn,
  "Courses".description,
  "Courses".enrolled,
  "Courses".extra_info,
  "Courses".final_exam,
  "Courses".flag_info,
  "Courses".fysem,
  "Courses".last_enrollment,
  "Courses".last_enrollment_same_professors,
  "Courses".listing_id,
  "Courses".locations_summary,
  "Courses".number,
  "Courses".professor_ids,
  "Courses".professor_names,
  "Courses".regnotes,
  "Courses".requirements,
  "Courses".rp_attr,
  "Courses".same_course_id,
  "Courses".same_course_and_profs_id,
  "Courses".last_offered_course_id,
  "Courses".school,
  "Courses".season_code,
  "Courses".section,
  "Courses".skills,
  "Courses".subject,
  "Courses".syllabus_url,
  "Courses".times_by_day,
  "Courses".times_summary,
  "Courses".title
FROM
  "Courses";