// Generated by https://quicktype.io

export interface SearchResponse {
	response: Response;
}

interface Response {
	data: Data;
}

interface Data {
	courses: Course[];
}

interface Course {
	description:                      string;
	title:                            string;
	areas:                            Area[];
	average_rating:                   number;
	average_rating_same_professors:   number;
	average_workload:                 number;
	average_workload_same_professors: number;
	computed_listing_infos_aggregate: ComputedListingInfosAggregate;
	course_id:                        number;
	locations_summary:                string;
	requirements:                     null | string;
	skills:                           Skill[];
	evaluation_narratives:            EvaluationNarrative[];
}

enum Area {
	Hu = "Hu",
	Sc = "Sc",
	So = "So",
}

interface ComputedListingInfosAggregate {
	nodes: Node[];
}

interface Node {
	all_course_codes:   string[];
	areas:              Area[];
	average_gut_rating: number;
	average_professor:  number;
	course_code:        string;
	crn:                number;
}

interface EvaluationNarrative {
	comment: string;
}

enum Skill {
	Qr = "QR",
	Wr = "WR",
}
