-- AlterTable
ALTER TABLE "courses" ALTER COLUMN "all_course_codes" SET DATA TYPE JSONB,
ALTER COLUMN "areas" SET DATA TYPE JSONB,
ALTER COLUMN "flag_info" SET DATA TYPE JSONB,
ALTER COLUMN "professor_ids" SET DATA TYPE JSONB,
ALTER COLUMN "professor_info" SET DATA TYPE JSONB,
ALTER COLUMN "professor_names" SET DATA TYPE JSONB,
ALTER COLUMN "skills" SET DATA TYPE JSONB,
ALTER COLUMN "times_by_day" SET DATA TYPE JSONB;
