// Generated by https://quicktype.io

export interface SearchResponse {
	data: Data;
}

export interface Data {
	computed_listing_info_aggregate: CoursesAggregate;
}

export interface CoursesAggregate {
	aggregate: Aggregate;
	nodes: Course[];
}

export interface Aggregate {
	count: number;
}

export interface Course {
	all_course_codes: string[];
	areas: Area[];
	course_code: string;
	credits: number | null;
	description: string;
	listing_id: number;
	same_course_id: number;
	season_code: string;
	skills: string[];
	title: string;
	course: CourseNested;
}

export enum Area {
	Hu = 'Hu',
	So = 'So'
}

export interface CourseNested {
	evaluation_narratives_aggregate_filtered: EvaluationNarrativesAggregateFiltered;
	evaluation_narratives_aggregate: EvaluationNarrativesAggregate;
}

export interface EvaluationNarrativesAggregate {
	aggregate: EvaluationNarrativesAggregateAggregate;
}

export interface EvaluationNarrativesAggregateAggregate {
	count: number;
	avg: Avg;
}

export interface Avg {
	comment_compound: number;
}

export interface EvaluationNarrativesAggregateFiltered {
	aggregate: EvaluationNarrativesAggregateAggregate;
	nodes: EvaluationNarrativesAggregateFilteredNode[];
}

export interface EvaluationNarrativesAggregateFilteredNode {
	comment: string;
	comment_compound: number;
}
